name: Code quality

on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'yarn.lock'
      - '**.js'
  pull_request:
    paths:
      - '.github/**'
      - 'yarn.lock'
      - '**.js'

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@master
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile
        if: steps.node_modules_cache.outputs.cache-hit != 'true'

      - run: yarn test
